package com.fnb.front.backend.controller.domain;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Getter
@Setter
@Entity
@Builder
@AllArgsConstructor // Required by JPA, generated by Lombok
@Table(name = "member_coupon")
public class MemberCoupon {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private int id;

    // Foreign Key to the Member entity (nullable = false is common)
    @Column(name = "member_id", nullable = false)
    private int memberId;

    // Foreign Key to the Coupon entity (nullable = false is common)
    @Column(name = "coupon_id", nullable = false)
    private int couponId;

    @Column(name = "is_used")
    private String isUsed;

    @Column(name = "status")
    private int status;

    // Using LocalDateTime for precise date and time tracking
    @Column(name = "issued_at", updatable = false)
    private LocalDateTime issuedAt;

    @Column(name = "used_at")
    private LocalDateTime usedAt;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id")
    private Member member;

    public MemberCoupon() {

    }
}