package com.fnb.front.backend.controller.domain;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.util.List;

@Getter
@Setter
@Entity
@AllArgsConstructor
@Builder// Required for JPA entities, generated by Lombok
@Table(name = "order_product")
public class OrderProduct {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false, nullable = false)
    private int orderProductId;

    @Column(name = "option_id", nullable = false)
    private String optionId;

    @Column(name = "order_id", nullable = false)
    private String orderId;

    @Column(name = "product_id", nullable = false)
    private int productId;

    @Column(name = "product_name")
    private String productName;

    @Column(name = "quantity")
    private int quantity;

    @Column(name = "option_name")
    private String optionName;

    @Column(name = "option_price")
    private BigDecimal optionPrice;

    // Monetary fields with defined precision/scale
    @Column(name = "payment_amount", precision = 19, scale = 2)
    private BigDecimal paymentAmount;

    @Column(name = "coupon_amount", precision = 19, scale = 2)
    private BigDecimal couponAmount;

    @Column(name = "discount_amount", precision = 19, scale = 2)
    private BigDecimal discountAmount;

    @Column(name = "coupon_id")
    private int couponId;

    @Transient
    private List<OrderAdditionalOption> orderAdditionalOptions;

    @Transient
    Product product;

    public OrderProduct() {

    }
}